title: MaximeRousseau.com
email: max@maximerousseau.com
name: Maxime Rousseau
description: ' '
navigation:
  - name: Home
    url: /
  - name: Mastodon
    url: https://bitcoinhackers.org/web/accounts/196363
  - name: LinkedIn
    url: https://www.linkedin.com/in/max302/
  - name: Github
    url: https://github.com/max302

baseurl: ""
url: "https://maximerousseau.com"
twitter_username: max302
github_username: max302

permalink: /:title/

paginate: 5

footer-text: ©2021 Maxime Rousseau

footer-links:
  email:
  github: max302
  instagram:
  linkedin: max302
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: #
  tumblr: #
  twitter: max302
  youtube: # channel/<your_long_string> or user/<user-name>

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

google_analytics:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - CNAME
